chore: upgrade `next`, `react` and `eslint` to latest compatible versions
Neste commit eu inicio utilizando o `codemod` do Next.js para atualizar
tanto o framework, quanto o React e de quebra o ESLint.

Um `codemod` é uma facilidade que uma empresa pode fornecer para fazer
por você as migrações de código e dependência necessárias para que o
sistema volte a ficar compatível.

Então primeiro rodei o comando principal do `codemod` apontando para uma
versão específica para eu e você continuarmos sincronizados:

```
npx @next/codemod upgrade 16.2.0
```

A primeira pergunta que o `codemod` fez foi se eu queria continuar no
React versão `18` e escolhi que não, que queria atualizar para a `19`.

Depois disso ele me listou todos os modificadores que ele iria aplicar
no código, escolhi aplicar todos, sendo que no nosso caso, o principal é
o abaixo dado que o Next.js não faz mais o tunelamento do linting para o
ESLint e agora devemos usar diretamente o ESLint:

```
next-lint-to-eslint-cli
```

Depois ele perguntou se queria então rodar o modificador do React 19 e o
modificador dos tipos, e respondi sim para ambos, mesmo não usando
TypeScript no projeto.

Só que ao tentar aplicar o `codemod` para valer, o `npm` reclamou de uma
incompatibilidade de `Peer Dependency`:

```
Upgrading your project to Next.js 16.2.0...
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: clone-tabnews@1.0.0
npm error Found: eslint@8.57.0
npm error node_modules/eslint
npm error   dev eslint@"8.57.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer eslint@">=9.0.0" from eslint-config-next@16.2.0
npm error node_modules/eslint-config-next
npm error   dev eslint-config-next@"16.2.0" from the root project
```

Em resumo, o `codemod` quer instalar o módulo `eslint-config-next` na
sua versão `16.2.0`, mas ele agora necessita que o módulo `eslint`
esteja no mínimo na versão `9.0.0` e o que está instalado no projeto é a
versão `8.57.0`. Dado a isso, o `npm` não consegue resolver essa
exigência na árvore de dependências e interrompe a instalação com um
erro.

Então eu desfiz todas as alterações que o `codemod` tentou fazer:

```
git checkout -- .
```

Reinstalei todas as dependências de novo para voltar como estava antes:

```
npm i
```

Atualizei todas as dependências relacionadas a ESLint da seguinte forma
antes de tentar de novo o `codemod`:

```
npm i -E eslint@10.0.3 eslint-config-next@16.2.0 \
  eslint-config-prettier@10.1.8 eslint-plugin-jest@29.15.0
```

O `npm` retornou alguns warnings a respeito de sobrescrever algumas peer
dependencies, mas instalou sem problemas.

Rodei de novo o `codemod` e ele começou a trabalhar de fato:

```
npx @next/codemod upgrade 16.2.0
```

Começou a aparecer um monte de coisa no terminal, até ele perguntar se
eu faço o deploy do meu app na Vercel, respondi que sim.

Mas infelizmente, final da história, o comando terminou com o seguinte
erro:

```
npm error code ECOMPROMISED
npm error Lock compromised
npm error A complete log of this run can be found in: /home/codespace/.npm/_logs/...
Error: Legacy codemod command failed with exit code: Some(1)
Error: Command failed: npx --yes codemod@latest react/19/migration-recipe --no-interactive
```

Doideira, então eu entendi que teria que arregaçar as mangas e continuar
de onde ele parou.

Analisando o repositório, o `codemod` alterou meu `package.json` com as
novas versões dos módulos e também alterou o `lint:eslint:check` para
apontar diretamente para o ESLint:

```
"lint:eslint:check": "eslint .",
```

Então decidi testar e ao rodar o ESLint através do script, quebrou:

```
npm run lint:eslint:check
```

Recebi um erro que começa desta forma:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@eslint/js' imported from ...
```

Investigando, o `codemod` no momento da migração leu o arquivo legado de
configuração do ESLint chamado `.eslintrc.json` e converteu ele para uma
nova versão chamado `eslint.config.mjs` e esta nova versão está pedindo
por um módulo chamado `@eslint/js` que não está instalado no projeto e,
de fato, não está.

Aí investigando na documentação de migração do ESLint no endereço
abaixo, eu vi que eles também fornecem um `codemod`:

https://eslint.org/docs/v10.x/use/configure/migration-guide

Então antes de rodar ele, removi o arquivo criado pelo `codemod` do
Next.js:

```
rm eslint.config.mjs
```

E rodei o `codemod` do ESLint:

```
npx @eslint/migrate-config .eslintrc.json
```

Ele rodou sem problemas, mas pelo menos me avisou:

```
You will need to install the following packages to use the new config:
- @eslint/js
- @eslint/eslintrc
```

Então eu instalei da seguinte forma:

```
npm i -E @eslint/js@10.0.1 @eslint/eslintrc@3.3.5
```

Rodei o script para testar de novo o ESLint:

```
npm run lint:eslint:check
```

E recebi um novo erro que começa com:

```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'configs' -> object with constructor 'Object'
```

Aí pensei: “Essa migração automática está um LIXO… o arquivo
`eslint.config.mjs` está um NOJO. Vou começar tudo do zero”... e o
primeiro passo foi desinstalar todos os módulos relacionados ao ESLint.

```
npm uninstall @eslint/js @eslint/eslintrc eslint \
  eslint-config-next eslint-config-prettier eslint-plugin-jest
```

Removi também o arquivo de configuração:

```
rm eslint.config.mjs
```

Daí fui para a documentação do módulo sobre como instalar ele, o
“Getting Started”, pra realmente começar do zero:

https://eslint.org/docs/v10.x/use/getting-started

E para nós dois rodarmos o mesmo comando, rode o seguinte:

```
npm init @eslint/config@1.11.0
```

De início o ESLint perguntou “What do you want to lint?” e eu escolhi
todas as opções:

```
◉ JavaScript
◉ JSON
◉ JSON with comments
◉ JSON5
◉ Markdown
◉ CSS
```

Depois ele perguntou “How would you like to use ESLint?” e escolhi:

```
▸ To check syntax and find problems
```

Depois ele perguntou “What type of modules does your project use?” e
escolhi:

```
▸ JavaScript modules (import/export)
```

Depois ele perguntou “Which framework does your project use?” e escolhi:

```
▸ React
```

Depois ele perguntou “Does your project use TypeScript?” e eu escolhi:

```
‣ No
```

Depois ele perguntou “Where does your code run?” e eu escolhi as duas
opções:

```
◉ Browser
◉ Node
```

Depois ele perguntou “What flavor of Markdown do you want to lint?” e eu
escolhi:

```
▸ GitHub Flavored Markdown
```

E então ele me avisou que iria instalar alguns pacotes e perguntou se eu
queria instalar eles agora, mas respondi que não! Respondi isso, porque
se não ele iria instalar a última versão dos pacotes e eu e você
poderíamos ficar dessincronizados.

Dado a isso, escolha a opção `No` também e instale manualmente comigo
estas versões:

```
npm i -E -D eslint@9.39.4 @eslint/js@9.39.4 globals@17.4.0 \
  @eslint/json@1.1.0 @eslint/markdown@7.5.1 @eslint/css@1.0.0 \
  eslint-config-next@16.2.0 eslint-plugin-jest@29.15.0 eslint-config-prettier@10.1.8
```

Dois detalhes:

1. Atualmente a versão mais atualizada do ESLint é a `10`, que foi
lançada faz pouco tempo e, dado a isso, estou instalando a `9` porque o
ecossistema de plugins ainda não conseguiu se atualizar e ficar
compatível com as novas APIs da versão `10`. Um dos plugins é o
`eslint-plugin-react` que é utilizado por baixo dos panos pelo
`eslint-config-next`.

2. No comando de instalação já aproveitei para instalar o
`eslint-config-next`, `eslint-plugin-jest` e `eslint-config-prettier`
para ficar compatível com o que tínhamos anteriormente.

Em paralelo a tudo isso, o `codemod` do ESLint deve ter criado um
arquivo chamado `eslint.config.mjs` com algumas configurações iniciais,
mas que para utilizar os plugins extras e continuar exatamente como
estava antes, utilize a versão do arquivo encontrada neste commit que
apenas inclui o uso dos plugins extras que utilizamos para linting do
Next.js, Jest e evitar conflito das regras do Prettier.

Outro detalhe é que, com a atualização do ESLint e a criação deste novo
arquivo de configuração, o arquivo anterior `.eslintrc.json` não é mais
utilizado e pode ser removido, então antes do commit eu executei:

```
git rm .eslintrc.json
```

E mais um detalhe interessante, agora proposto pelo aluno
`rodrigofinkler`, é fazer o ESLint retornar um `exit code` acima de `0`
também para `warnings` para, por exemplo, quebrar o pipeline do CI caso
encontre alguma situação assim. Então o script do npm ficou desta forma:

```
"lint:eslint:check": "eslint . --max-warnings 0",
```

Por fim, rodei um `npm test` para entender se a camada da aplicação
estava ok e para minha surpresa estava tudo ok, todos os testes
rodaram 100%.

Também subi manualmente o servidor web com `npm run dev`, testei a
página do `/status` e também tudo funcionando 100%.

Último teste foi fazer um erro proposital no código para ver se o novo
ESLint continuaria quebrando o fluxo no CI e quebrou com sucesso e daí
parti para o commit final que é este que você está lendo neste exato
momento.

Próximo passo vai ser testar criação e ativação de usuários lá na URL de
homologação para ver se tudo continua ok.